### ISSUE TITLE
Count time reported this week

### ISSUE THREAD

**Issue by approximator** [approximator/waied#2]
Here is todo: https://github.com/approximator/waied/blob/master/src/taskmanager.cpp#L80

All the time calculations are done using this library: https://github.com/HowardHinnant/date

**Comment by SergeyKarasyov** [comment]
I want to work on it!

**Comment by SergeyKarasyov** [comment]
I think usage of boost::gregorian may have sense here.

**Comment by approximator** [comment]
But all the time calculations are done using this library: https://github.com/HowardHinnant/date
